servers=[
  {
    :hostname => "wazuh-server",
    :ip => "192.168.100.10",
    :box => "ubuntu/bionic64",
    :ram => 2048,
    :cpu => 4
  },
  {
    :hostname => "wazuh-agent",
    :ip => "192.168.100.11",
    :box => "ubuntu/bionic64",
    :ram => 1024,
    :cpu => 2
  }
]


Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
                vb.gui = false
                vb.name = machine[:hostname]
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
                vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
                vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
                vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
                vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
            end
            node.vm.synced_folder "./ansible", "/ansible"
            node.vm.provision:shell, path: "bootstrap.sh"
        end
    end
end